### ISSUE TITLE
[SUGGESTION] Script Section in Config

### ISSUE THREAD

**Issue by ImExiled** [musiqpad/mqp-server#99]
Add a section where you can put the link to the main launch file of a script/extension (Ex. NCS) which will load the script of site load.

Like:

// If you want to use a script like NCS, paste its link here. It is not required to run the pad.
var script = "https://rawgit.com/bentenz5/NCS/master/ncs.js";

**Comment by DerpgonCz** [comment]
If you are a self-hosted pad owner and wish to load custom scripts on a self-hosted front-end, then it is easy to add a line that loads the file.

If otherwise (official pad, self-hosted using out front-end) then we'd like to keep integrity and not support any major changes officially without the user actually needing to download something and actively agree with it.

**Comment by explodingcamera** [comment]
For self-hosted servers, we're working on https://github.com/musiqpad/mqp-server/tree/server_modules and for official servers, this would be a huge security threat.

**Comment by DerpgonCz** [comment]
Self hosted pads (with self hosted FE) can add this directly to the code.
Any pads that uses our FE or official pads will only allow extensions with the confirmation from a user - aka a user HAS TO install / run the extension himself.
